# Generated by Django 2.2.16 on 2023-01-26 03:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0004_auto_20230125_2300'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipes',
            old_name='ingredient',
            new_name='ingredients',
        ),
    ]
