# Generated by Django 2.2.16 on 2023-01-26 03:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0005_auto_20230126_0633'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='IngredientInRecipe',
            new_name='IngredientsInRecipe',
        ),
    ]
