# Generated by Django 2.2.16 on 2023-01-26 10:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0006_auto_20230126_0635'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ingredientsinrecipe',
            name='ingredients',
        ),
        migrations.AddField(
            model_name='ingredientsinrecipe',
            name='ingredient',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='ingredients', to='recipes.Ingredients'),
            preserve_default=False,
        ),
    ]
