# Generated by Django 2.2.16 on 2023-01-29 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0004_auto_20230129_1619'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='favourites',
            options={'ordering': ('-pub_date',), 'verbose_name_plural': 'Любимые рецепты'},
        ),
        migrations.AlterModelOptions(
            name='shoppingcart',
            options={'ordering': ('-pub_date',), 'verbose_name_plural': 'Рецепты в списке покупок'},
        ),
    ]
