# Generated by Django 2.2.16 on 2023-02-09 22:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0007_auto_20230210_0030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='name',
            field=models.CharField(max_length=200, validators=[django.core.validators.RegexValidator(message='Введите корректное название рецепта', regex='^[А-Яа-яA-Za-z\\s]+$')], verbose_name='Название'),
        ),
    ]
