# Generated by Django 2.2.16 on 2023-02-10 00:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0009_auto_20230210_0313'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='name',
            field=models.CharField(help_text='Только буквы, пробелы разрешены.', max_length=200, validators=[django.core.validators.RegexValidator(message='Введите корректное название рецепта', regex='^[А-Яа-яA-Za-z\\s]+$')], verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.CharField(max_length=200, unique=True, verbose_name='Название тега'),
        ),
    ]
