# Generated by Django 2.2.16 on 2023-02-21 15:34

from django.db import migrations, models
import recipes.validators


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0010_auto_20230210_0353'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='image',
            field=models.ImageField(upload_to='recipes/images', validators=[recipes.validators.image_size], verbose_name='Фото'),
        ),
    ]
