# Generated by Django 2.2.16 on 2023-02-08 19:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20230208_1424'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='follow',
            options={'ordering': ('-id',), 'verbose_name_plural': 'Подписки'},
        ),
    ]
